
site_name: vortex2d
site_description: "A lightweight 2D vortex particle method with Gaussian cores"
site_url: https://<your-user>.github.io/<your-repo>
repo_url: https://github.com/<your-user>/<your-repo>
repo_name: <your-user>/<your-repo>

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - toc.follow
    - content.code.copy
    - content.code.select
    - content.action.edit
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            separate_signature: true
            heading_level: 2
            filters:
              - "!^_"

nav:
  - Home: index.md
  - Theory:
      - Primer: theory/primer.md
      - Gaussian core & Biot–Savart: theory/gaussian_core_biot_savart.md
      - Diffusion: theory/diffusion_core_spreading_vs_pse.md
  - Guides:
      - Quickstart (Lamb–Oseen): guides/quickstart_lamb_oseen.md
      - Dipole & speed check: guides/dipole.md
      - Periodic boundaries: guides/periodic_bcs.md
      - Animation export: guides/animation_export.md
  - API Reference:
      - vortex2d.vortex2d: api/vortex2d.md
      - vortex2d.api (I/O & configs): api/api.md
      - vortex2d.plotly_viz: api/plotly_viz.md

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
