
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - uses: snok/install-poetry@v1

      - name: Install dependencies
        run: |
          poetry --version
          poetry install --with dev,plot || poetry install --with dev

      - name: Lint & type
        run: |
          poetry run ruff check .
          poetry run ruff format --check
          poetry run mypy src

      - name: Run tests
        run: poetry run pytest -q

      - name: Build validation plots
        env:
          ARTIFACTS_DIR: artifacts
        run: poetry run python scripts/make_validation_plots.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: validation-plots
          path: artifacts
          if-no-files-found: error
