
name: publish

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # for trusted publishing (if enabled on PyPI)
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.4

      - name: Build sdist and wheel
        run: |
          poetry build
          ls -lah dist/

      - name: Publish to PyPI (trusted publishing)
        if: ${{ github.event_name != 'workflow_dispatch' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist

      - name: Manual publish using token (fallback)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          if [ -z "$PYPI_API_TOKEN" ]; then
            echo "PYPI_API_TOKEN secret not set. Skipping."
          else
            python -m pip install --upgrade twine
            python -m twine upload -u __token__ -p "$PYPI_API_TOKEN" dist/*
          fi
